name: 'PushS3PreSignAction'
description: 'Push file to S3 & create cloudfront presign-url'
inputs:
  aws-region:
    description: 'Aws region'
    default: "eu-central-1"
  aws-role:
    description: 'Aws role to apply changes'
    required: true
  files-list:
    description: 'Comma separated list of file to upload'
    required: true
  destination:
    description: ''
    required: true
  s3-bucket-name:
    description: ''
    required: true
  distribution:
    description: ''
    required: true
  key-pair-id:
    description: ''
    required: true
  private-key:
    description: ''
    required: true
runs:
  using: 'composite'
  steps:
    # Configure aws credentials
    - name: Configure AWS credentials for security
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region}}
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: OIDCSession
    # Upload files to s3
    - name: Upload file to s3
      shell: bash
      env:
        FILES: ${{ inputs.files-list }}
      run: |
        set -e
        files=$(echo $FILES | tr "," "\n")
        for file in $files; do
          if [ -f $file ]; then
            aws s3 cp $file s3://${{ inputs.s3-bucket-name }}/${{ inputs.destination}} --recursive
          else
            echo "::error file=$file,line=1::File is missing"
            exit 1
          fi
        done
    - name: Create presign cloudfront
      shell: bash
      env:
        FILES: ${{ inputs.files-list }}
      run: |
        set -e
        files=$(echo $FILES | tr "," "\n")
        echo "Presign Url for artefact" >> $GITHUB_STEP_SUMMARY
        echo "${{ inputs.private-key }}" > private_key.pem
        for file in $files; do
          name="$(basename -- $file)"
          echo "File ${name}" >> $GITHUB_STEP_SUMMARY
          url=$(aws cloudfront sign --url https://${{ inputs.distribution }}/${{ inputs.destination }}/$name --key-pair-id ${{ inputs.key-pair-id }} --private-key file://private_key.pem --date-less-than 2023-12-12)
          echo "${url}" >> $GITHUB_STEP_SUMMARY
        done
