name: 'PushS3PreSignAction'
description: 'Push file to S3 & create cloudfront presign-url'
inputs:
  aws-region:
    description: 'Aws region'
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  files-list:
    description: 'Comma separated list of file to upload'
    default: ''
  destination:
    description: 'Path to S3 destination'
    default: ''
  s3-bucket-name:
    description: 'S3 bucket name'
    default: ''
  distribution:
    description: 'Cloudfront dns'
    default: ''
  key-pair-id:
    description: 'Cloudfront public key pair id'
    default: ''
  private-key:
    description: 'Cloudfront presign private key'
    default: ''
  date-less-than:
    description: 'Expiration date for presigned url YYYY-MM-DD, default today + 1 month'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated FinalCAD/PushS3PreSignAction
      shell: bash
      run: |
        echo "::error title=Deprecated FinalCAD/PushS3PreSignAction::The action FinalCAD/PushS3PreSignAction is deprecated. Don't use it!"
        exit 1
